### ISSUE TITLE
I am trying to run Quiver I get this error

### ISSUE THREAD

**Issue by Subhi** [PacificBiosciences/pbcore#111]
I am trying to run Quiver :  
However I get the following error, my input is a bam file and reference.fasta file. 

Running job quiver-lv (7370641) on 
'HD'
Traceback (most recent call last):
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcommand-0.6.1-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/l/python2.7/lib/python2.7/site-packages/GenomicConsensus-2.2.0-py2.7.egg/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/home/l/python2.7/lib/python2.7/site-packages/GenomicConsensus-2.2.0-py2.7.egg/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2649, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1936, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 477, in __init__
    self.updateCounts()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2490, in updateCounts
    self.assertIndexed()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2320, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1893, in _assertIndexed
    self._openFiles()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2017, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 196, in __init__
    self._checkFileCompatibility()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 185, in _checkFileCompatibility
    checkedVersion = self.version
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 271, in version
    return self.peer.header["HD"]["pb"]
KeyError: 'HD'
[ERROR] 'HD'
Traceback (most recent call last):
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcommand-0.6.1-py2.7.egg/pbcommand/cli/core.py", line 136, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/home/l/python2.7/lib/python2.7/site-packages/GenomicConsensus-2.2.0-py2.7.egg/GenomicConsensus/main.py", line 381, in args_runner
    return tr.main()
  File "/home/l/python2.7/lib/python2.7/site-packages/GenomicConsensus-2.2.0-py2.7.egg/GenomicConsensus/main.py", line 297, in main
    with AlignmentSet(options.inputFilename) as peekFile:
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2649, in __init__
    super(AlignmentSet, self).__init__(*files, **kwargs)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1936, in __init__
    super(ReadSet, self).__init__(*files, **kwargs)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 477, in __init__
    self.updateCounts()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2490, in updateCounts
    self.assertIndexed()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2320, in assertIndexed
    self._assertIndexed((IndexedBamReader, CmpH5Reader))
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 1893, in _assertIndexed
    self._openFiles()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/dataset/DataSetIO.py", line 2017, in _openFiles
    resource = IndexedBamReader(location)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 385, in __init__
    super(IndexedBamReader, self).__init__(fname, referenceFastaFname)
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 196, in __init__
    self._checkFileCompatibility()
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 185, in _checkFileCompatibility
    checkedVersion = self.version
  File "/home/l/python2.7/lib/python2.7/site-packages/pbcore-1.4.0-py2.7.egg/pbcore/io/align/BamIO.py", line 271, in version
    return self.peer.header["HD"]["pb"]
KeyError: 'HD'

**Comment by mdsmith** [comment]
Hi Subhi, what did you use to generate your bam file? It looks like it has a malformed header. Can you post the header here?

**Comment by pb-dseifert** [comment]
RSII support has been removed.
