### ISSUE TITLE
test failure with numpy 1.16: dtype of to_begin must be compatible with input ary

### ISSUE THREAD

**Issue by RizzerOnGitHub** [PacificBiosciences/pbcore#120]
pbcore tests fail under numpy 1.16 (currently 1.16.0.rc2), with message "arraysetops.py TypeError: dtype of to_begin must be compatible with input ary".  It involves BasH5IO.py, invoking numpy arraysetops.

Failing test logs can be seen at https://ci.debian.net/packages/p/python-pbcore/unstable/amd64/

The same failure is seen in build logs at https://tests.reproducible-builds.org/debian/rbuild/unstable/amd64/python-pbcore_1.5.0+git20180606.43fcd9d+dfsg-2.rbuild.log.gz

Those logs are for pbcore 1.5.0(git20180606), but the error still occurs with 1.6.5.

A sample from a 1.6.5 build is:

ERROR: test_pbcore_io_AlnFileReaders.TestBasicBam.testBaxAttaching
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/projects/misc/build/python-pbcore/tests/test_pbcore_io_AlnFileReaders.py", line 293, in testBaxAttaching
    self.f.attach(self.BAX_FILE)
  File "/home/projects/misc/build/python-pbcore/pbcore/io/align/_AlignmentMixin.py", line 22, in attach
    self.basH5Collection = BasH5Collection(fofnFilename)
  File "/home/projects/misc/build/python-pbcore/pbcore/io/BasH5IO.py", line 818, in __init__
    for k, v in groupby(movieNamesAndFiles, lambda t: t[0]) ])
  File "/home/projects/misc/build/python-pbcore/pbcore/io/BasH5IO.py", line 662, in __init__
    self._parts = [ BaxH5Reader(self.filename) ]
  File "/home/projects/misc/build/python-pbcore/pbcore/io/BasH5IO.py", line 328, in __init__
    self._loadRegions(self.file)
  File "/home/projects/misc/build/python-pbcore/pbcore/io/BasH5IO.py", line 355, in _loadRegions
    self._regionTableIndex = _makeRegionTableIndex(self.regionTable.holeNumber)
  File "/home/projects/misc/build/python-pbcore/pbcore/io/BasH5IO.py", line 284, in _makeRegionTableIndex
    to_begin=[1], to_end=[1])
  File "/usr/lib/python2.7/dist-packages/numpy/lib/arraysetops.py", line 111, in ediff1d
    raise TypeError("dtype of to_begin must be compatible "
TypeError: dtype of to_begin must be compatible with input ary

**Comment by llimeht** [comment]
The discussion at https://github.com/numpy/numpy/issues/12711 and https://github.com/numpy/numpy/pull/12713 may render this change unneeded, but it will do no harm to be more explicit about the data types here.
